### PR TITLE
Fix extension stuck on building on windows platform

### PR DESCRIPTION
**Pull request by omeshp**

### CODE REVIEW

**Comment by omeshp** [comment]
@prashaantt Does these changes look good? spawning npm fails on windows as suggested in issue https://github.com/nodejs/node/issues/3675 we should be using npm.cmd.

**Comment by prashaantt** [comment]
Thanks a ton for this @omeshp! I think I'd arrived at a similar solution when I tried to fix it, but didn't know it was a legit bug in Node itself and so I couldn't be sure. I'll take a look at the linked bug and get hang of a Windows machine (hopefully this week itself) to test out your code and merge.

**Comment by prashaantt** [comment]
@omeshp I ended up handling this [slightly differently](https://github.com/prashaantt/node-tdd/commit/45ec59896acf3799c9a04ed177a7d32b4a083b9c). Thanks for your PR regardless!

**Comment by omeshp** [comment]
@prashaantt ok cool!

**Pull request closed without merging**
